added folders homework
lesia-mk/test-project pull request #4
Opened 2018-10-20 21:57 UTC by lesia-mk

2018-10-20 22:00 UTC, lesia-mk commented
![image](https://user-images.githubusercontent.com/44004871/47260888-710e9c80-d4cc-11e8-9abc-63fa4a68ddb7.png)
![image](https://user-images.githubusercontent.com/44004871/47260891-8d123e00-d4cc-11e8-9acd-8bd15f25750b.png)
![image](https://user-images.githubusercontent.com/44004871/47260900-ad41fd00-d4cc-11e8-9510-6023201de43c.png)

2018-10-21 19:23 UTC, spolischook requested changes
```name``` attribute is missed for fields

I've suggest use ```div``` as wrapper for form fields instead of ```p```, however Yana suggest use ```li``` and I'm agree, because it's semantically right

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                <input id="name" type="text" value="325">
readonly or disabled attribute should be applied

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                <input id="password" type="password" value="123456789">
remove value attribute it's prohibited here

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +    <form action="#" name="secondForm" method="post">
form should be one on the page in context of this HW

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                <select name="select">
```suggestion
                <select name="country">
```

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                    <option value="ua">Ukraine</option>
:+1:

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                <select name="select">
Preferred choices is missed. See wire-frame

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                <input type="checkbox" name="a" value="html" checked>HTML
```suggestion
                <input type="checkbox" name="skills" value="html" checked>HTML
```

2018-10-21 19:23 UTC, spolischook commented on HW2/table and form.html
> +                <input type="hidden" id="author" name="author" value="Lesia">
:+1:

2018-10-21 20:17 UTC, spolischook commented on HW2/table and form.html
> +                <input id="id" name="id"type="text" value="325">
don't forget about ```readonly``` or ```disabled``` attribute

2018-10-21 20:51 UTC, spolischook commented on HW2/table and form.html
> +                <input id="id" name="id"type="text" value="325" readonly>
:sun_with_face:

2018-11-07 17:32 UTC, merged